### ISSUE TITLE
Question: divergent palettes

### ISSUE THREAD

**Issue by famuvie** [sjmgarnier/viridis#20]
Is there any recommendation about what to use as a divergent colour palette?
e.g. to clearly visually tell apart positive from negative values?

**Comment by sjmgarnier** [comment]
@famuvie If by divergent you mean a palette which maximum (or minimum) intensity value corresponds to zero, then you find it here. Such palettes are problematic because some values at least (if not all) on the left and right of the midpoint will be indistinguishable when printed in black and white, and for colorblind people, which is exactly what the 4 palettes in the `viridis` package try to avoid.

Personally I do not see a problem - and would actually recommend now - using the continuous palettes in `viridis` for representing the transition between negative and positive values.

**Comment by famuvie** [comment]
I mean [this kind](http://colorbrewer2.org/?type=diverging&scheme=BrBG&n=9) of palette, based on shades of two different colours. The `viridis` palettes conveys a sense of sequence (which it is), while a diverging palette gives a sense of increments in two *divergent* directions (e.g. positives and negatives).

I find them very intuitive and useful to immediately distinguish zones *above* or *below* the mean (or 0), and based of the intensity, to tell how far from the mean they are. See [example](http://rpubs.com/famuvie/breedR-splines).

However I'm also concerned about colorblindness, and perceptual uniformity. Therefore the question. Thanks.

**Comment by sjmgarnier** [comment]
@famuvie Yes, we're talking about the same thing. The example palettes in your link have their maximum intensity value corresponding to the midpoint of the data spread (or to zero in your case), meaning that most of them won't play well with colorblindness (tick the 'colorblind safe' box, and a lot of them disappear already), and even less well with prints (tick the 'print friendly' or 'photocopy safe' boxes and you're left with nothing). 

While they might seem more intuitive, I don't think anymore that they should be used (even though I used them a lot in the past. e.g. http://tinyurl.com/q86jynm). With a proper scale to your graph, I think people should have no problem reading your results correctly.

**Comment by jan-glx** [comment]
what do you think of: http://www.kennethmoreland.com/color-maps/

**Comment by talgalili** [comment]
I just came across this today, and it looks great:
http://stackoverflow.com/questions/37482977/what-is-a-good-palette-for-divergent-colors-in-r-or-can-viridis-and-magma-b/

**Comment by famuvie** [comment]
Good @jan-glx !! Glad someone proposed something with a scientific basis.
I didn't go through the paper yet, but I don't see a big difference with respect to the blue-white-red scheme. In addition, I quite don't understand the reason for using some gray in the middle, which reduces the contrast sensibly.
In any case, bravo!
