### ISSUE TITLE
scale_color_viridis() with scale_colour_viridis() alias

### ISSUE THREAD

**Issue by ginolhac** [sjmgarnier/viridis#22]
Thanks for a great package! Heatmaps with the `viridis` looks real nice and the fact to see the contrast in black & white mode is a plus.
As a small enhancement, it would be nice to have the non American English spelling `colour` as an alias for the existing `color` functions. I am somehow used to @hadley's style and write `scale_colour` all the time. That doesn't break anything in `ggplot2`. Of low priority obviously.

**Comment by sjmgarnier** [comment]
@ginolhac This is certainly possible. I will try to include this in the next version of the package.

**Comment by sjmgarnier** [comment]
@ginolhac On CRAN now.

**Comment by ginolhac** [comment]
Thanks a lot @sjmgarnier ! Have a nice evening!

**Comment by sjmgarnier** [comment]
@ginolhac Thanks!
