### ISSUE TITLE
A color scale with white in the middle?

### ISSUE THREAD

**Issue by talgalili** [sjmgarnier/viridis#34]
Hi there,
I love viridis. 
However, I want some color scale where the middle point gets the black or white color. I couldn't find this between the existing color schemes. Is there one like that which I've missed?

Thanks!

**Comment by sjmgarnier** [comment]
@talgalili This is by design. Besides being colorblind friendly, these color maps are meant to be "perceptually-uniform, both in regular form and also when converted to black-and-white". A color map that has a black or white midpoint would not be perceptually uniform when converted to black-and-white (i.e. the same level of gray would end up representing two different values on each side of the midpoint).

**Comment by talgalili** [comment]
Thanks @sjmgarnier for the explanation. What you write make sense.
My problem is with things like a correlation matrix. I want to show extreme values of high and low correlations, but I also want to ignore correlations which are too close to zero so that they are not significant.
What do you think?

**Comment by sjmgarnier** [comment]
@talgalili I don't see how a color map with a black or white midpoint would help here. Maybe I don't really understand what you're trying to do.

**Comment by talgalili** [comment]
For example, when using the corrplot package, I want to remove the non-significant correlations - but that would just leave a white background - so the question is what background to use. 

https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html


![image](https://cloud.githubusercontent.com/assets/976006/14508733/93147d5c-01d1-11e6-8003-3894a0b838b0.png)

**Comment by talgalili** [comment]
Compare the above to this:

library(corrplot)
M <- cor(mtcars)
`corrplot(M, method = "circle", col = viridis::viridis(100))
`


![image](https://cloud.githubusercontent.com/assets/976006/14508815/f928b252-01d1-11e6-8148-c3e41b597b28.png)

**Comment by talgalili** [comment]
mmm, maybe this (but it doesn't look so good)

`corrplot(M, method = "circle", col = viridis::viridis(100), bg = viridis::viridis(100)[50])`
 
![image](https://cloud.githubusercontent.com/assets/976006/14508863/36493648-01d2-11e6-8c1f-bdc2c3481e76.png)


Sorry for the multiple comments. I'm done :)

**Comment by sjmgarnier** [comment]
@talgalili This is not really the right place to look for help. I suggest that you post your question on Stackoverflow instead. You're more likely to get answers there on how to improve the graphical representation of your data. Traditionally, correlation matrices are represented as is, with the value of the correlation in each box, and different text colors to differentiate significant correlations from non-significant ones.

**Comment by talgalili** [comment]
Thank you for the response. You are right, I'll ask this on SO. Have a great day :)
