### ISSUE TITLE
scale_fill_viridis() does not fill ggplot2 bar geoms colors

### ISSUE THREAD

**Issue by jrosen48** [sjmgarnier/viridis#45]
Thanks for a great package!

I am trying to fill bars using `geom_col()` (which is equivalent to `geom_bar(stat = "identity")` in a `ggplot2` bar plot with colors using `scale_fill_viridis(discrete = T)` :

```
library(tidyverse)
library(viridis)

mtcars %>% 
    select(cyl, mpg) %>% 
    group_by(cyl) %>% 
    summarise(mpg_mean = mean(mpg)) %>% 
    ggplot(aes(x = cyl, y = mpg_mean)) +
    geom_col() +
    scale_fill_viridis(discrete = T)
```

![mpg](https://cloud.githubusercontent.com/assets/4596214/24367318/34750606-12ea-11e7-9451-926deab672a6.png)

This does not seem to color the bars. Is there a way to use `scale_fill_viridis()` to do this?

**Comment by sjmgarnier** [comment]
@jrosen48 Looks like you didn't specify an aesthetic for "fill". This works for me: 

```
mtcars %>% 
  select(cyl, mpg) %>% 
  group_by(cyl) %>% 
  summarise(mpg_mean = mean(mpg)) %>% 
  ggplot(aes(x = cyl, y = mpg_mean, fill = factor(cyl))) +
  geom_col() +
  scale_fill_viridis(discrete = T)
```

**Comment by jrosen48** [comment]
That did the trick. Oops! Thanks
