### ISSUE TITLE
unknown committer

### ISSUE THREAD

**Issue by ashander** [sjmgarnier/viridis#5]
looks great but who is the 'unknown' committer? Someone with push access but no setting for `user.name` or `user.email` in git config, perhaps? To test, in a shell

```sh
$ git config --global -l | grep user
```
should read out user name and email. I not, then set by

```sh
$ git config --global user.name "John Doe"
$ git config --global user.email johndoe@example.com
```

more details see [these instructions](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup)

**Comment by sjmgarnier** [comment]
@ashander It should have been me, but I'm not sure what happened here.

**Comment by sjmgarnier** [comment]
@ashander It seems that it is a problem with SourceTree that was not properly configured on my other computer.

**Comment by sjmgarnier** [comment]
Sourcetree on Windows created other problems as well. It's corrected now. Closing this issue. Thanks for pointing out the problem.

**Comment by ashander** [comment]
No problem. I figured it could be something weird, as you seem plenty
git(hub) savvy.

Cool scale! Thanks for porting it
