### ISSUE TITLE
Viridis 0.5 needs ViridisLite 0.3

### ISSUE THREAD

**Issue by cderv** [sjmgarnier/viridis#52]
I had an error when installing Viridis because I already had ViridisLite 0.2.
```
Error : object ‘cividis’ is not exported by 'namespace:viridisLite'
ERROR: lazy loading failed for package ‘viridis’
```
This function was added in version 0.3
https://github.com/cran/viridisLite/commit/989f5cf2c3b8c1c2856df6e87ec95a06a97c4dc6

`DESCRIPTION` needs to be updated to depends on viridisLite (>= 0.3) not (>= 0.2). 
it could also be an opportunity to change depends to imports ? (see #49)

**Comment by sjmgarnier** [comment]
@cderv Yes, there is an error in the DESCRIPTION file. Viridis requires viridisLite 0.3 now. Update viridisLite and all should work. I will update the DESCRIPTION file for the next update.

**Comment by sjmgarnier** [comment]
Closed by 92624eb

**Comment by cderv** [comment]
> Update viridisLite and all should work. 

it is what I have done. I was just reporting the error. Thanks a lot !

**Comment by sjmgarnier** [comment]
@cderv Thanks!

**Comment by zeruniverse** [comment]
I still got the `viridisLite` error when trying `install.packages('viridis')`

```
* installing *source* package ‘viridis’ ...
** package ‘viridis’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error : object ‘cividis’ is not exported by 'namespace:viridisLite'
ERROR: lazy loading failed for package ‘viridis’
* removing ‘/home/jeffery/R/x86_64-pc-linux-gnu-library/3.4/viridis’
Warning in install.packages :
  installation of package ‘viridis’ had non-zero exit status
```

However, I'm able to install using this: `devtools::install_github("sjmgarnier/viridis")`

**Comment by sjmgarnier** [comment]
@zeruniverse Yes, it's an error in the CRAN package that doesn't import the right version of viridisLite. Just update viridisLite and it should work.

**Comment by zeruniverse** [comment]
I was just reporting it that the CRAN package does not work. I already installed using GitHub repo.
