### ISSUE TITLE
When using discrete=T, scale always starts at extremes

### ISSUE THREAD

**Issue by matthewravery** [sjmgarnier/viridis#55]
When using `scale_colour_viridis(discrete = T)`, I often don't want to have the most extreme yellow as one of my three or five color choices. It's just too bright for some folks. Selecting discrete scale endpoints towards the middle of the scale or at least making this an option would be very helpful.

**Comment by sjmgarnier** [comment]
@matthewravery Check the `begin` and `end` arguments, I believe this is what you are looking for. 

Also note that `viridis` and the associated color maps were designed with continuous scales in mind. The `discrete` option is provided for convenience/compatibility with `ggplot2`. There are more suitable palettes for discrete scales (e.g. see `scale_color_colorblind` in the `ggthemes` package).
