### ISSUE TITLE
Dependency on viridisLite should be 0.3, not 0.2

### ISSUE THREAD

**Issue by vzemlys** [sjmgarnier/viridis#56]
I tried installing the package and got bitten by #53 and #47 . I installed the new version of `viridisLite` and everything worked. Then I tried to replicate the procedure on another machine. I used `dependencies=TRUE` but I had the version 0.2 of viridisLite. With this version loading the `viridis` package failed. So I suggest that the depends should be bumped to`>=0.3` for `viridisLite`.

**Comment by sjmgarnier** [comment]
@vzemlys It's done on Github, I haven't pushed it to CRAN yet.
