### ISSUE TITLE
New "Turbo" colormap

### ISSUE THREAD

**Issue by noamross** [sjmgarnier/viridis#65]
Google's released a new "Turbo" map that is designed as a replacement for "Jet".  It is designed as a compromise between viridis-type maps and the useful many-color properties of rainbow maps.  It doesn't quite meet the stringent rules colors in this package meet, but it does have a coherent philosophy and some distinct advantages:

https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html .

Should we include Turbo in `viridis`? Inclusion in viridis makes it rapidly available in ggplot2 and lots of other packages, which is helpful if the purpose is to serve people who want these popular maps. On the other hand it makes `viridis` less coherent.  If so, we probably want to modify the vignette to explain the difference.

**Comment by noamross** [comment]
Some action on this already: https://gist.github.com/jlmelville/be981e2f36485d8ef9616aef60fd52ab

**Comment by sjmgarnier** [comment]
@noamross I don't mind including it but don't really have the bandwidth to work on viridis at the moment. There are still a couple of PRs pending and it's in need of being updated on CRAN. The best I can do is mid-September I'm afraid.

**Comment by talgalili** [comment]
I think it would be great, but it sounds like something that is worth its
own package, no?

**Comment by thomasp85** [comment]
We've had loose discussions about using it as a basis for some of our colour scales, but nothing more... If it ends up being part of standard ggplot2 then import is something we'd have to consider, but anyone is free to create palette packages

**Comment by talgalili** [comment]
Your reasons makes sense, I support adding turbo to this package.

**Comment by yutannihilation** [comment]
From ggplot2's side, I don't find any argument against this. It's viridis to decide what options it should have.

OTOH, as a user of viridis, I would say this is concerning.

> On the other hand it makes viridis less coherent.

Matplotlib seems to give it a try. Can we wait for their conclusion? I think now viridis package can be considered as "a collection of newer color pallets in matplotlib", so, if matplotlib is to implement Turbo, I think it's natural viridis package also gets that option.
 https://github.com/matplotlib/matplotlib/issues/15091

**Comment by sjmgarnier** [comment]
> As such, it should probably be implemented in a scale function that provides a midpoint argument, and neither `scale_color_viridis_c()` nor `scale_color_viridis_d()` do so

They do have a `begin` and `end` argument. Maybe not ideal but that should be enough for a savvy user to change the location of the midpoint, no?

**Comment by yutannihilation** [comment]
> As such, it should probably be implemented in a scale function that provides a midpoint argument,

FWIW, `scale_*_distiller()` provides diverging colour palettes without midpoint (c.f.  https://ggplot2.tidyverse.org/reference/scale_brewer.html).

**Comment by yutannihilation** [comment]
It seems the next release of matplotlib will include Turbo.

https://github.com/matplotlib/matplotlib/pull/15275

**Comment by sjmgarnier** [comment]
@noamross `turbo` is now in `viridisLite`. I'll work on updating `viridis` accordingly very soon.

**Comment by yutannihilation** [comment]
I'm preparing pull requests on scales and ggplot2 just to reflect the new options to their docs.

* https://github.com/r-lib/scales/pull/306
* https://github.com/tidyverse/ggplot2/pull/4412

**Comment by sjmgarnier** [comment]
@yutannihilation Thanks! I submitted `viridisLite` to CRAN yesterday, awaiting final approval from them. Then, I will do the reverse dependence checks for `viridis` (can't do it until `viridisLite` is on CRAN) before preparing the CRAN submission. That might not be before the end of the week depending on how fast I hear back from CRAN.

**Comment by yutannihilation** [comment]
Congrats on the CRAN release! :tada:

**Comment by sjmgarnier** [comment]
@yutannihilation Thanks! It's just viridisLite for now. I need to change a few things in viridis to resolve a reverse dependence issue. Hopefully tomorrow.

**Comment by sjmgarnier** [comment]
@yutannihilation I just got confirmation that viridis is on its way to CRAN.

**Comment by yutannihilation** [comment]
Thanks. To be clear, users are already able to use new options with ggplot2 if they installed the newest version of viridisLite. The only problem is the documentation; ggplot2 refers to the documentation of scales package, and I expect the new version of scales package won't be released anytime soon, so I expect ggplot2's documentation will stay the old description for a while, unfortunately... Anyway, it's out of the scope of this issue. Congrats on the CRAN release of viridis too!

**Comment by sjmgarnier** [comment]
@yutannihilation I know. I was just letting you (and everyone else) know why I'm closing this issue.

**Comment by yutannihilation** [comment]
I see, thanks.
