### ISSUE TITLE
install viridis Error in rbind(info, getNamespaceInfo(env, "S3methods")) : number of columns of matrices must match (see arg 2)

### ISSUE THREAD

**Issue by chrisdane** [sjmgarnier/viridis#79]
Hi

When I try to install the viridis packeg, I get the following error: 
```r
version
# platform       x86_64-pc-linux-gnu
# version.string R version 3.5.3 (2019-03-11)
install.packages("viridis")
...
* DONE (viridisLite)
...
* installing *source* package ‘viridis’ ...
** package ‘viridis’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in rbind(info, getNamespaceInfo(env, "S3methods")) : 
  number of columns of matrices must match (see arg 2)
ERROR: lazy loading failed for package ‘viridis’
```

Thanks a lot for any help,
Chris

**Comment by sjmgarnier** [comment]
@chrisdane Unfortunately, I can't reproduce this error on my Ubuntu installation with R 3.5.3. This seems to be an issue with your local R installation. Maybe this can help: https://stackoverflow.com/questions/55925357/error-in-rbindinfo-getnamespaceinfoenv-s3methods-when-installing-factoex

**Comment by chrisdane** [comment]
Sorry dont know anymore what finally solved this. Sorry for spam :(
