### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [sjmgarnier/viridis#87]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by sjmgarnier** [comment]
@rsbivand Thanks for the heads up. I'm preparing an update that, hopefully, will come in the new year (time permitting). These packages are all in the "suggests" category and are only useful for the vignettes. It should be easy to remove them without affecting the package.

**Comment by rsbivand** [comment]
[00check.log](https://github.com/sjmgarnier/viridis/files/11141560/00check.log)
is a recent check log from running under `_SP_EVOLUTION_STATUS_=2` without retiring r-spatial packages (suggested in this package) on the library path. The minimal correction is to check that the package namespaces can be loaded, and if not, do not run those parts of the examples. It would be safer in the longer term to replace retiring r-spatial packages with active r-spatial/rspatial packages (see https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html).

**Comment by rsbivand** [comment]
Please also see https://r-spatial.org/r/2023/04/10/evolution3.html, fix best by June, latest October 2023.

**Comment by sjmgarnier** [comment]
@rsbivand This should be fixed in 1a7283e2c637a426323acad66ed0d2a5624dfe24 and 3fe8b63299e9d0795fa95d2cf5f8ff270c3ab3d1.

**Comment by rsbivand** [comment]
Thanks for your co-operation, looks good!
